name: GitHub Label Update

on: workflow_dispatch

jobs:
  update_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/github-labels.yml
          skip-delete: false
          dry-run: false
          exclude:
